//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotosProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonsMedia
    {
        public int MediaId { get; set; }
        public int PersonsId { get; set; }
        public int Id { get; set; }
    
        public virtual Media Media { get; set; }
        public virtual Persons Person { get; set; }
    }
}
